# Generated by Django 5.2.4 on 2025-07-13 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('resumo', models.TextField()),
                ('ano', models.DateField(auto_now_add=True)),
                ('empresa_publicada', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, upload_to='pictures/%Y/%m')),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('publicado_por', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
