# Generated by Django 5.2.4 on 2025-07-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_generos_alter_livros_publicado_por_livros_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
